# Generated by Django 5.2.5 on 2026-06-29 22:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FazendaAcesso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('perfil', models.CharField(choices=[('ADMIN', 'Administrador da fazenda'), ('OPERADOR', 'Operador'), ('VETERINARIO', 'Veterinário'), ('CONSULTOR', 'Consultor')], default='OPERADOR', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('can_view_rebanho', models.BooleanField(default=True)),
                ('can_create_rebanho', models.BooleanField(default=False)),
                ('can_update_rebanho', models.BooleanField(default=False)),
                ('can_delete_rebanho', models.BooleanField(default=False)),
                ('can_view_pastagem', models.BooleanField(default=True)),
                ('can_create_pastagem', models.BooleanField(default=False)),
                ('can_update_pastagem', models.BooleanField(default=False)),
                ('can_delete_pastagem', models.BooleanField(default=False)),
                ('can_view_financeiro', models.BooleanField(default=False)),
                ('can_create_financeiro', models.BooleanField(default=False)),
                ('can_update_financeiro', models.BooleanField(default=False)),
                ('can_delete_financeiro', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos', to='core.fazenda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fazenda_acessos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('farm', 'usuario'), name='unique_fazenda_usuario_acesso')],
            },
        ),
    ]
