# Generated by Django 5.2.5 on 2026-06-29 22:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fazendaacesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(choices=[('avicultura', 'Avicultura'), ('suinocultura', 'Suinocultura'), ('ovinocultura', 'Ovinocultura'), ('bovinocultura', 'Bovinocultura'), ('gestao', 'Gestão multi-cultura'), ('manejo', 'Manejo'), ('nutricao', 'Nutrição e ração'), ('sanidade', 'Sanidade e enfermaria'), ('producao', 'Produção'), ('financeiro', 'Financeiro'), ('iot', 'IoT')], max_length=40, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_create_gestao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_create_manejo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_create_nutricao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_create_producao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_create_sanidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_delete_gestao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_delete_manejo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_delete_nutricao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_delete_producao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_delete_sanidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_update_gestao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_update_manejo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_update_nutricao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_update_producao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_update_sanidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_view_gestao',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_view_manejo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_view_nutricao',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_view_producao',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fazendaacesso',
            name='can_view_sanidade',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='FazendaModulo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('liberado', models.BooleanField(default=True)),
                ('liberado_em', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='core.fazenda')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fazendas', to='core.modulosistema')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('farm', 'modulo'), name='unique_fazenda_modulo')],
            },
        ),
    ]
