# Generated by Django 5.2.5 on 2026-06-30 00:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_modulosistema_fazendaacesso_can_create_gestao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logacao',
            options={'ordering': ['-data_hora']},
        ),
        migrations.AddField(
            model_name='logacao',
            name='caminho',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logacao',
            name='dados',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='logacao',
            name='metodo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='logacao',
            name='status_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logacao',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logacao',
            name='acao',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('DELETE', 'Remoção'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('BACKUP', 'Backup'), ('SECURITY', 'Segurança'), ('OTHER', 'Outra')], max_length=20),
        ),
        migrations.AlterField(
            model_name='logacao',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fazenda'),
        ),
        migrations.AlterField(
            model_name='logacao',
            name='registro_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super administrador'), ('ADMIN', 'Administrador'), ('FAZENDEIRO', 'Fazendeiro'), ('FUNCIONARIO', 'Funcionário'), ('VETERINARIO', 'Veterinário')], default='FUNCIONARIO', max_length=20),
        ),
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ativo', models.BooleanField(default=False)),
                ('frequencia', models.CharField(choices=[('DIARIO', 'Diário'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal')], default='DIARIO', max_length=20)),
                ('hora_execucao', models.TimeField(default='02:00')),
                ('destino', models.CharField(default='backups', max_length=255)),
                ('manter_ultimos', models.PositiveIntegerField(default=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ultima_execucao_em', models.DateTimeField(blank=True, null=True)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_config', to='core.fazenda')),
            ],
        ),
        migrations.CreateModel(
            name='BackupExecucao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUCESSO', 'Sucesso'), ('ERRO', 'Erro')], max_length=20)),
                ('arquivo', models.CharField(blank=True, max_length=500, null=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='core.backupconfig')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_execucoes', to='core.fazenda')),
            ],
            options={
                'ordering': ['-iniciado_em'],
            },
        ),
    ]
