# Generated by Django 5.2.5 on 2026-06-30 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_logacao_options_logacao_caminho_logacao_dados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fazenda',
            name='ramo_atuacao',
            field=models.CharField(choices=[('AVICULTURA_POSTURA', 'Avicultura de postura'), ('AVICULTURA_CORTE', 'Avicultura de corte'), ('SUINOCULTURA', 'Suinocultura'), ('OVINOCULTURA', 'Ovinocultura'), ('BOVINOCULTURA', 'Bovinocultura'), ('CAPRINOCULTURA', 'Caprinocultura'), ('PISCICULTURA', 'Piscicultura'), ('MULTICULTURA', 'Multicultura'), ('OUTRA', 'Outra')], default='MULTICULTURA', max_length=40),
        ),
        migrations.AddField(
            model_name='fazenda',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fazendas_responsavel', to=settings.AUTH_USER_MODEL),
        ),
    ]
