# Generated by Django 5.2.5 on 2025-09-02 01:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_brincos', models.CharField(max_length=50, unique=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('nascimento', models.DateField()),
                ('peso_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('raca', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fazenda')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAnimal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('PESO', 'Peso'), ('VACINA', 'Vacina'), ('MOV', 'Movimentação'), ('REPROD', 'Reprodução')], max_length=20)),
                ('valor', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_evento', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='rebanho.animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fazenda')),
            ],
        ),
        migrations.CreateModel(
            name='Rebanho',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_lote', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fazenda')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='rebanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animais', to='rebanho.rebanho'),
        ),
    ]
