# Generated by Django 5.2.5 on 2025-10-24 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('financeiro', '0001_initial'),
        ('rebanho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rebanho.animal'),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fazenda'),
        ),
    ]
