# Generated by Django 5.2.5 on 2025-10-23 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('financeiro', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamentofinanceiro',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fazenda'),
        ),
    ]
